task:
  name: rom
  only_if: $CIRRUS_REPO_OWNER == 'NFS86'
  timeout_in: 240m
  container:
    image: anggit86/ubuntu:21.10
    cpu: 8
    memory: 32G
    
  env:
    BUILD_HOSTNAME: "nfs-project"
    rcloneconfig: "ENCRYPTED[44ffa3857f6328b03c137af6abf4f1aed91717c51cb06ae8c8fae74d96c0e8cc473a802fa8328e48c414c2de236fe21d]"
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_CPU: 10
    CIRRUS_WORKING_DIR: /home/cirrus-ci-build

  Environment_script:
     - cat /etc/os* && env && nproc && gcc --version && clang --version
     - mkdir -p ~/.config/rclone
     - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
  
  Load_rom_script:
     - ./load.sh

  Storage-Check_script:
     - df -h && lsblk && ls -l -a -h
     
  Sync_rom_script:
     - ./sync.sh
  
  Build_rom_script:
     - set -e
     - name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
     - device=$(grep unch $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d ' ' -f 2 | cut -d _ -f 2 | cut -d - -f 1)
     - mkdir -p $CIRRUS_WORKING_DIR/rom/$name_rom
     - cd $CIRRUS_WORKING_DIR/rom/$name_rom
     - export ALLOW_MISSING_DEPENDENCIES=true
     - export CCACHE_DIR=$CIRRUS_WORKING_DIR/ccache
     - export CCACHE_EXEC=$(which ccache)
     - export USE_CCACHE=1
     - export CCACHE_COMPRESS=true
     - export PATH="/usr/lib/ccache:$PATH"
     - which clang
     - ccache -o run_second_cpp=true
     - ccache -o depend_mode=true
     - ccache -o direct_mode=true
     - ccache -o file_clone=true
     - ccache -o inode_cache=true
     - ccache -M 0
     - ccache -F 0
     - ccache - a fast C/C++ compiler cache
     - ccache -c && ccache -z
     - command=$(tail $CIRRUS_WORKING_DIR/build.sh -n +$(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) - 1)| head -n -1 | grep -v '# upload rom')
     - bash -c "$command"
     
  Ccache_info_script:
     - set -e
     - name_rom=$(grep init $CIRRUS_WORKING_DIR/build.sh -m 1 | cut -d / -f 4)
     - export CCACHE_DIR=$CIRRUS_WORKING_DIR/rom/$name_rom/ccache
     - ccache -s

  Upload_build_script:
     - ./ziping.sh
